version: '3.8'

services:
  api:
    build: ./Restapi
    volumes:
      - ./Restapi:/usr/src/app
    ports:
      - 5001:5001
  

  website:
    build: ./Web
    volumes:
      - ./Web:/usr/src/app
    ports:
      - 5000:5000
